# Generated by Django 3.0.5 on 2020-06-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
